development:
  adapter: postgresql
  encoding: unicode
  database: rwb_dev
  pool: 5
  host: localhost
  port: 5432  
   

test:
  adapter: postgresql
  encoding: unicode
  database: rwb_test
  pool: 5
  host: localhost
  port: 5432  